spring:
  datasource:
    url: jdbc:h2:mem:mybatis
    username: sa
    password: 
  h2:
    console:
      enabled: true
mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
  type-aliases-package: com.yhdatabase.domain