CREATE TABLE members (
	id BIGINT PRIMARY KEY AUTO_INCREMENT ,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL
);
CREATE TABLE authorities (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	member BIGINT NOT NULL,
	name VARCHAR(50) NOT NULL
);